---
title: "Plot For Review"
format: html
editor: visual
author: "Tomer Zipori"
---

### Loading libraries

```{r}
#| output: false
library(tidyverse)
library(tidytuesdayR)
library(remotes)

# remotes::install_github("thomas-neitmann/scalesextra")
library(scalesextra)
```

### Loading Data

```{r}
tuesdata <- tidytuesdayR::tt_load('2023-01-17')

data <- tuesdata$artists

glimpse(data)
```

### The 'Artists' dataset

From the 'tidytuesday' Github repo: The 'Artists' dataset contains various information about artists by edition of Gardner or Janson's art history textbook from 1926 until 2020. Data includes demographic information, space occupied in the textbook, as well as presence in the MoMA and Whitney museums.

### Cleaning

```{r}
data_clean <- data %>%
  select(year, artist_gender, artist_race_nwi, space_ratio_per_page_total) %>%
  mutate(artist_identity = paste(artist_race_nwi, artist_gender)) %>%
  filter(!grepl("N/A" ,artist_identity))

data_clean <- data_clean %>%
  group_by(year, artist_identity) %>%
  summarise(space_ratio = mean(space_ratio_per_page_total, na.rm = T),
            .groups = "drop")
```

### Plotting

```{r}
plot <- data_clean %>%
  ggplot(aes(x = year, y = space_ratio, fill = artist_identity, col = artist_identity)) +
  geom_point(show.legend = F) +
  geom_line() +
  scale_color_manual(values = c("#4285F4", "#34A853", "#FBBC05", "#EA4335")) +
  scale_x_continuous(breaks = seq(min(data_clean$year), max(data_clean$year), by = 10)) +
  scale_y_pct() +
  xlab("Year of publish") +
  ylab("Average area dedicated to artist (cm^2)") +
  labs(title = "Printing space dedicated to artists of different identites in art history textbooks",
       subtitle = "Showing the average % of page space dedicated to text and figure of artists in textbooks") +
  guides(col = guide_legend(title = "Artist Identity", reverse = T)) +
  theme_classic()

plot

# ggsave("artists_v2.png", plot = plot, path = "plots/", width = 16, height = 9)
```
